language: php
php:
  - '7.2'
#  - hhvm # on Trusty only
#  - nightly
branches:
  only:
  - feature/cypress
env:
  - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
      -  xvfb
      - libgtk2.0-0
      - libnotify-dev
      - libnss3
      - libxss1
      - libasound2
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
node_js:
  - '8.9.4'
before_script:
  - cd api
  - composer update
  - cd ..
  - cd webapp
  - npm install
  - cd ..
  - bash ./deploy.sh
  - sudo chmod -R 777 api/storage/
  - docker-compose up -d --build
script:
  - docker ps
  - cd webapp
#  - npm run cypress:run
  - curl --get http://localhost/v1/sistema
  - curl --get http://localhost/v1/acount
#  - docker exec comunication-webapp npm install
#  - docker exec comunication-webapp cypress install
#  - docker exec comunication-webapp npm run cypress:run
  - $(npm bin)/cypress run
