language: node_js

branches:
  only:
  - feature/cypress
env:
  - DOCKER_COMPOSE_VERSION=2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker-compose up -d
  - docker ps
node_js:
  - '8.9.4'

    #before_script:
    #- docker-compose up -d
    #- docker ps
script:
  - bash ./deploy.sh
