language: node_js

branches:
  only:
  - feature/cypress
env:
  - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
      -  xvfb
      - libgtk2.0-0
      - libnotify-dev
      - libnss3
      - libxss1
      - libasound2
node_js:
  - '8.9.4'

    #before_script:
    #- docker-compose up -d
    #- docker ps
before_script:
  - bash ./deploy.sh
  - docker-compose up -d
script:
  - docker ps
  - cd webapp
  - npm install
#  - docker exec comunication-webapp $(npm bin)/cypress run
